// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace PhotoMSK.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class updateRoutes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateRoutes));
        
        string IMigrationMetadata.Id
        {
            get { return "201411180841174_updateRoutes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
