// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace PhotoMSK.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class StudioAdress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudioAdress));
        
        string IMigrationMetadata.Id
        {
            get { return "201406211228576_StudioAdress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
