// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace PhotoMSK.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class HallProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HallProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201502081249221_HallProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
