// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace PhotoMSK.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class PageCategory_CategoryName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PageCategory_CategoryName));
        
        string IMigrationMetadata.Id
        {
            get { return "201502251745348_PageCategory_CategoryName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
